# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Master Branch Deploy

#on:
#  release:
#    types: [created]

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 #https://github.com/actions/checkout
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Build with Maven
        run: mvn -B package --file $GITHUB_WORKSPACE/pom.xml -P github

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -P github
        env:
          GITHUB_TOKEN: ${{ github.token }}
        id: publish
      # This step prints an output (time) from the previous step's action.
      - name: Echo the Publish time
        run: echo 'The time was ${{ steps.publish.outputs.time }}.'